{
	"data": "ENC[AES256_GCM,data:dM0XwIFberZVr/ELpAGEV72VcsKvO80eKdvGyaTxKtcsarota9ckPLIdjjiDabuD53bdnQ/AbxmkKpAEscS+IA6OTVN0tFdOItBGgTqhi4EXpWCGlSgYANCiykVOSqIP/lb1nFWf+qzjrtts78pfuCezgURCfd8y73nMmq+jQBO0l2RIjJmru/RiyURn01YLT5S6pI6lA3uCvG+PWi6KTTSCXXXyb6uhtphvpIoap98VmJNSPj5bkGtFbR6EelzpWoe0jzcCxKYtA3dxUYdVqSdJk9b+l8iR1GpUcWlcRgfcKgV+eIdMrlcHjDtb25Ljn7KoaDChW4ZGXqszBDcyCZIBWUow3r4rWqqLTmuR1/6O/2jkBBQGTYGMszQ90E89aLeG9xyASbKC4uTAklsTkTcKn+X3,iv:YMoFNn8R610bWcMKbQJ85750pwCnWqtH0i/0UydV6+U=,tag:0eM5SJtYh+BpfPQiNnfQVg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1gnuydcffmwalyeqr7pmgp26nnwg4smwum05atpunh3xnfz0a5cnsc6erzf",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQmd3SFhVM1piT0lCZEJm\nZmhYNldhV0JUNjdkTiszOWZ4aE5MU1lwaWhVCnJ0UWhFazZoNHBJODhKTnFEOUg4\nUE5kb2oxOWVmTEpjVW9RdDQwaUNpUkEKLS0tIGtwSUx1K1Q1L0VyeHdxMGRYeUMv\nck84RU0xT1Z5ck5FSFNGZTVMWmdGdW8KUxazAvxdCXoCDhDFRMGO62WnGnHDqUH6\n8SK4BKQfoYX0tIgQ+Ev7GmOydM8Bk7V/zlMjxMsLV4v4+txAtaAhUA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-01-24T16:26:41Z",
		"mac": "ENC[AES256_GCM,data:M97YyWIBZN1FTSueyjyCQUWVjh7GMxvXGsUBwCCohDBjl32YiqjEh58WOedmrHD+h4efeQ/vptFckZT0pydl61wtUr7+vgRIeVLibwqSBGCgoEgLKj874BpMMzqhpzyrG0/i5Wbx7Q17+yzvA/dLXSh+BJZB7M7qOepzmDRnweY=,iv:iWjnR8p8HSWqElR8E2FG2HOvStnHe1w9o1lJ/T8VeYU=,tag:mTmI0Mu4tinbCGPSUH7f3A==,type:str]",
		"version": "3.11.0"
	}
}
